cmake_minimum_required(VERSION 3.22)
project(iris_pyrowave LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(pyrowave-shared SHARED IMPORTED)
set_target_properties(pyrowave-shared PROPERTIES IMPORTED_LOCATION "${PYROWAVE_LIBRARY}")
add_library(iris-pyrowave SHARED renderer.cpp)
target_include_directories(iris-pyrowave PRIVATE "${PYROWAVE_SOURCE}" "${PYROWAVE_SOURCE}/Granite/third_party/khronos/vulkan-headers/include")
target_link_libraries(iris-pyrowave PRIVATE pyrowave-shared vulkan android log)
target_compile_options(iris-pyrowave PRIVATE -Wall -Wextra -Werror -Wno-missing-field-initializers)
target_link_options(iris-pyrowave PRIVATE -Wl,-z,max-page-size=16384)
